services:
  db:
    container_name: db-notes-app-dev
    image: postgres:16
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: server-notes-app-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"

  client:
    container_name: client-notes-app-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

volumes:
  pgdata:
