services:
  db:
    container_name: db-notes-app
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

  server:
    container_name: server-notes-app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    depends_on:
      - db

  client:
    container_name: client-notes-app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    depends_on:
      - server
