services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=sajawal
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default
    ports:
      - "5432:5432"

  server:
    container_name: server-notes-app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    container_name: client-notes-app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
