FROM node:20

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . .
RUN npm run build

COPY docker-entrypoint.prod.sh docker-entrypoint.prod.sh
RUN chmod u+x docker-entrypoint.prod.sh

EXPOSE 5000

CMD [ "bash", "./docker-entrypoint.prod.sh" ]