FROM node:20

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

RUN npm i

EXPOSE 3000

# Install pg_utility
RUN apt-get update && apt-get install -y postgresql-client

# For Prisma
COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

CMD [ "/app/docker-entrypoint.sh" ]