FROM node:20

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

RUN npm i

COPY src/ src/

EXPOSE 3000

CMD [ "npm", "run", "dev" ]