on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci

      - name: Containerize server
        run: docker build -f ./server/Dockerfile.prod -t server-notes-app:latest
      - name: Containerize client
        run: docker build -f ./client/Dockerfile.prod -t client-notes-app:latest

      - name: Tag the images
        run: |
          docker tag server-notes-app:latest sajawal1f12/server-notes-app:latest
          docker tag client-notes-app:latest sajawal1f12/client-notes-app:latest

      - name: Push to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
