on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [server, client]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup QEMU for Docker
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}/package-lock.json', matrix.service)) }}

      - name: Install deps
        run: |
          cd ${{ matrix.service }}
          npm ci

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag, build & push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: true
          tags: |
            sajawal1f12/${{ matrix.service }}-notes-app:latest
            sajawal1f12/${{ matrix.service }}-notes-app:${{ github.sha }}
          cache-from: type=registry,ref=sajawal1f12/${{ matrix.service }}-notes-app:cache
          cache-to: type=registry,ref=sajawal1f12/${{ matrix.service }}-notes-app:cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no sajawalhassan_1feb@34.123.231.175 "
            cd /home/sajawalhassan_1feb/website &&
            sudo docker compose pull &&
            sudo docker compose up -d
          "
