on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [server, client]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4

      - name: Install deps
        run: |
          cd ${{ matrix.service }}
          npm ci

      - name: Create Docker build
        run: |
          cd ${{ matrix.service }}
          docker build -f Dockerfile.prod -t ${{ matrix.service }}-notes-app .

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & Push
        run: |
          docker tag ${{ matrix.service }}-notes-app sajawal1f12/${{ matrix.service }}-notes-app:latest
          docker tag ${{ matrix.service }}-notes-app sajawal1f12/${{ matrix.service }}-notes-app:${{ github.sha }}

          docker push sajawal1f12/${{ matrix.service }}-notes-app:latest
          docker push sajawal1f12/${{ matrix.service }}-notes-app:${{ github.sha }}
